<%@ page language="java" import="support.*, java.util.*, sql_helper.*" contentType="text/html; charset=GB18030"
    pageEncoding="GB18030"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
 	<title>Name</title>
 	<link href="${pageContext.request.contextPath}/css/bootstrap.css" rel="stylesheet">
 	<script src="js/bootstrap.min.js"></script>
 	<script src="http://code.jquery.com/jquery-latest.js"></script>
	<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
 	<script text="javascript">
 	(function($,W,D)
 			{
 			    var JQUERY4U = {};
 			 
 			    JQUERY4U.UTIL =
 			    {
 			        setupFormValidation: function()
 			        {
 			            //form validation rules
 			            $("#register-form").validate({
 			                rules: {
 			                    first_name: "required",
 			                    last_name: "required"
 			                },
 			                messages: {
 			                    first_name: "Please enter your firstname",
 			                    last_name: "Please enter your lastname"
 			                },
 			                submitHandler: function(form) {
 			                    form.submit();
 			                }
 			            });
 			        }
 			    }
 			 
 			    //when the dom has loaded setup form validation rules
 			    $(D).ready(function($) {
 			        JQUERY4U.UTIL.setupFormValidation();
 			    });
 			 
 			})(jQuery, window, document);
 	</script>
 	<script text="javascript">
 		function checkForm()
 		{
 			var lastname = document.getElementById("lastname").value;
 			var firstname = document.getElementById("firstname").value;
 			var middlename = document.getElementById("middlename").value;
			var lastBoolean = false;
			var firstBoolean = false;
			var middleBoolean = true;
 			var patterns = /^[a-z]*$/i; 		    
 		    if (lastname.match(patterns)) 
 		   {
 		    	lastBoolean = true;
 		   }
 		    else
 		   {
 		    	alert('Only allow character for the last name field, please try again');
 		   }	
 		    
 		   if (firstname.match(patterns)) 
 		   {
 		    	firstBoolean = true;
 		   }
 		    else
 		   {
 		    	alert('Only allow character for the first name field, please try again');
 		     	
 		   }	
 		  if (middlename.match(patterns)) 
		   {
		    	middlenameBoolean = true;
		   }
		    else
		   {
		    	alert('Only allow character for the middle name field, please try again');
		    	middlenameBoolean = false;
		   }
 		   if(lastBoolean && firstBoolean && middlenameBoolean)
 			   {
 			   		return true;
 			   }
 		   else
 		   {
 				return false;   
 		   }
 		}

 		
 	</script>
 </head>
 <%
 	HashMap degree_list = new HashMap(); //We want to use hashmap to store degreeList, each
 	//degree is a degreeInfo class object and has a unique id generated by code, and we use this
 	//id as key value and degreeInfo class as value, and store it into degree_list hashmap object
 	//so when we want to delete one degree we can use the unique key to locate the value
 	session.setAttribute("degree_list", degree_list);

 %>
		 <body>
		  <fieldset style="background: none repeat scroll 0 0 #F9F8F3;">
		  	<legend>Personal Information</legend>
		  	<form method="GET" action="address.jsp" id="register-form" novalidate="novalidate"  onSubmit="return checkForm()">	
		  	<h3>Full legal Name</h3>		  
		  	  <div class="container-fluid">
				  <div class="row-fluid">
				  		
				  		<!-- First Name part -->
					    <div class="span2">
					    	<label>
					  			<span style="margin-left:130px;">First Name</span>
					  		</label>
					  	</div>
					  	<div class="span9 fieldgroup">     		      
					  			<input id="firstname" type="text"  maxlength="50" size="25" name="first_name">
						</div>
						
						<!-- Last Name part -->
						<div class="span2">
					    	<label>
					  			<span style="margin-left:100px;">Last Name</span>
					  		</label>
					  	</div>
					  	<div class="span9 fieldgroup" style="margin-left:0px;">					      			      
					  			<input id="lastname" type="text"  maxlength="50" size="25" name="last_name">
						</div>
						
						<!-- Middle Name part -->
						<div class="span2">
					    	<label>
					  			<span style="margin-left:100px;">Middle Initial</span>
					  		</label>
					  	</div>
					  	<div class="span9" style="margin-left:0px;">					      			      
					  			<input id="middlename" type="text" maxlength="50" size="25" name="middle_name">
						</div>
						
						<!-- Country part -->
						<div class="span2">
					    	<label>
					  			<span style="margin-left:100px;">Country</span>
					  		</label>
					  	</div>
					  	<div class="span8" style="margin-left:0px;">					      			      
							<select name="country">
								<% //Here we read country list from text file instead of Postgre database
								DB_Helper dbHelper = new DB_Helper();
							    Vector<String> countries = dbHelper.fetchCountry();
							    
							    for(int i = 0; i < countries.size(); i++)
							    {       							
								%><option value="<%=(countries.get(i))%>">  
								<%=(countries.get(i))%></option>
								
								<%
								} 
								%>

							</select>				  	
					  	</div>
					  		
						<div class="span8" style="margin-left:300px;">					      			      
					  			<input type="submit" name="submit" value="Submit Personal Data" >						
					  	</div>
					
				   </div>
			   </div>
			 </form>
		  </fieldset>			  
		 </body>
</html>
